type: object
description: Метаданные пагинации
properties:
  page:
    type: integer
    format: int32
    description: Текущая страница
  per_page:
    type: integer
    format: int32
    description: Количество элементов на странице
  total:
    type: integer
    format: int64
    description: Всего элементов
  total_pages:
    type: integer
    format: int32
    description: Всего страниц
required:
  - page
  - per_page
  - total
  - total_pages
